### ISSUE TITLE
Error when running setup.py (or using pip):  [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: ...

### ISSUE THREAD

**Issue by gitttt** [noxdafox/clipspy#1]
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

```
c:\tmp\clipspy\clipspy>python setup.py install
Traceback (most recent call last):
  File "C:\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Python37\lib\http\client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "C:\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Python37\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "C:\Python37\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\package_index.py", line 765, in open_url
    return open_with_auth(url, self.opener)
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\package_index.py", line 959, in _socket_timeout
    return func(*args, **kwargs)
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\package_index.py", line 1078, in open_with_auth
    fp = opener(request)
  File "C:\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Python37\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 91, in <module>
    "License :: OSI Approved :: BSD License"
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\__init__.py", line 130, in setup
    _install_setup_requires(attrs)
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\__init__.py", line 125, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\dist.py", line 514, in fetch_build_eggs
    replace_conflicting=True,
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\pkg_resources\__init__.py", line 773, in resolve
    replace_conflicting=replace_conflicting
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\pkg_resources\__init__.py", line 1056, in best_match
    return self.obtain(req, installer)
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\pkg_resources\__init__.py", line 1068, in obtain
    return installer(requirement)
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\dist.py", line 581, in fetch_build_egg
    return cmd.easy_install(req)
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\command\easy_install.py", line 664, in easy_install
    not self.always_copy, self.local_index
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\package_index.py", line 654, in fetch_distribution
    dist = find(requirement)
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\package_index.py", line 634, in find
    loc = self.download(dist.location, tmpdir)
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\package_index.py", line 578, in download
    found = self._download_url(scheme.group(1), spec, tmpdir)
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\package_index.py", line 823, in _download_url
    return self._attempt_download(url, filename)
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\package_index.py", line 829, in _attempt_download
    headers = self._download_to(url, filename)
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\package_index.py", line 728, in _download_to
    fp = self.open_url(url)
  File "C:\Users\vagrant\AppData\Roaming\Python\Python37\site-packages\setuptools\package_index.py", line 779, in open_url
    % (url, v.reason))
distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/ca/f2/e375b7469a2dfe9d1feac81a10df97f18cd771b9a10ac62ca9864b760f7c/cffi-1.11.5-cp37-cp37m-win_amd64.whl#sha256=495c5c2d43bf6cebe0178eb3e88f9c4aa48d8934aa6e3cddb865c058da76756b: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045
```)

**Comment by gitttt** [comment]
This solved the problem on Windows 10:
`pip install certifi`

**Comment by noxdafox** [comment]
This is not an issue with `clipspy` but a known issue with [pip](https://github.com/pypa/pip/issues/4205) on Windows.

Usually is recommended to update `pip` to the latest version.

**Comment by gitttt** [comment]
FYI: Updating pip was not enough in my case.
