### ISSUE TITLE
ModuleNotFoundError: No module named 'clips._clips'

### ISSUE THREAD

**Issue by gitttt** [noxdafox/clipspy#3]
On Windows Server 2016, python 3.7, importing clips gives me the below error, no matter if installed using `pip install clipspy` or built by myself.

```
PS C:\tmp\clipspy> python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win3
Type "help", "copyright", "credits" or "license" for more information.
>>> import clips
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\tmp\clipspy\clips\__init__.py", line 30, in <module>
    from clips.error import CLIPSError
  File "C:\tmp\clipspy\clips\error.py", line 32, in <module>
    from clips.router import Router
  File "C:\tmp\clipspy\clips\router.py", line 5, in <module>
    from clips._clips import lib, ffi
ModuleNotFoundError: No module named 'clips._clips'
```

**Comment by noxdafox** [comment]
Looking at the traceback, it seems you are still importing from `C:\tmp\clipspy` which is where you temporarily built `clipspy` and not the installation location.

Are you sure you are setting the right Python import path?
