### ISSUE TITLE
ModuleNotFoundError: No module named 'clips._clips'

### ISSUE THREAD

**Issue by charlet-antoine** [noxdafox/clipspy#31]
Hey there,
I've installed your library on RedHat7.3 VM from the sources using the Makefile provided and everything worked as expected during the process. However when I'm trying to make an Import in the python interpreter I've got the following message: 

>>> import clips
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "clips/__init__.py", line 30, in <module>
    from clips.error import CLIPSError
  File "clips/error.py", line 32, in <module>
    from clips.router import Router
  File "clips/router.py", line 7, in <module>
    from clips._clips import lib, ffi
ImportError: No module named _clips

Indeed I don't see any module named _clips in the package. Do you have any idea where I'm missing something ? 

Thanks for your help.

**Comment by noxdafox** [comment]
Hello,

`clipspy` comes as wheel package, therefore you should be able to easily install it via `pip`.

May I ask you why you are going down the Makefile road?

**Comment by noxdafox** [comment]
Closing this due to inactivity. Please re-open if necessary.
