### ISSUE TITLE
installation in pycharm fails

### ISSUE THREAD

**Issue by dobrowol** [noxdafox/clipspy#43]
While installing clipspy in Pycharm on Windows via Settings->Project Interpreter I get error 

```
Collecting clipspy
  Using cached https://files.pythonhosted.org/packages/10/e8/87c3293255eb3beb328c2c0af7e9b768b066c395417c626dfc3a04e5b725/clipspy-0.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\wodobrow\AppData\Local\Temp\pycharm-packaging\clipspy\setup.py", line 73, in <module>
        long_description=read('README.rst'),
      File "C:\Users\wodobrow\AppData\Local\Temp\pycharm-packaging\clipspy\setup.py", line 36, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "C:\Users\wodobrow\AppData\Local\Programs\Python\Python38\lib\encodings\cp1250.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 77: character maps to <undefined>
    
    ----------------------------------------
```

python version 3.8
setuptools version 56.0.0

**Comment by noxdafox** [comment]
Fixed on `1.0.0`.
