### ISSUE TITLE
No module named 'clips._clips' & Can't use pip

### ISSUE THREAD

**Issue by farazex1** [noxdafox/clipspy#46]
Hey there
 Having successfully  installed the package using "sudo make install" ( after chaning python to python3 in the 1st line) , I get the following error as I try to import clips
```
>>> import clips
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/pythonClips/clipspy/clips/__init__.py", line 56, in <module>
    from clips.environment import Environment
  File "/home/pi/pythonClips/clipspy/clips/environment.py", line 32, in <module>
    from clips.facts import Facts
  File "/home/pi/pythonClips/clipspy/clips/facts.py", line 47, in <module>
    from clips.modules import Module
  File "/home/pi/pythonClips/clipspy/clips/modules.py", line 40, in <module>
    from clips.common import CLIPSError
  File "/home/pi/pythonClips/clipspy/clips/common.py", line 33, in <module>
    from clips._clips import lib, ffi
ModuleNotFoundError: No module named 'clips._clips'
```
Why not use pip ? I am trying to use the package on raspberry pi , and of course have been able to compile clips on raspberry.
Any suggestions ?
thanks in advance

**Comment by noxdafox** [comment]
Closing this issue due to inactivity.
